development:
  GMAIL_USERNAME: 'enviosyarq'
  GMAIL_PASSWORD: 'enviosyarq2017'
  URL: 'https://obligatorio1-erreperez.c9users.io/signup'
  URLAPIKG: 'https://delivery-rates.mybluemix.net/'
  USERAPI: '180121'
  PASSWORDAPI: 'EDQBtYNNP2H1'
  
  
production:
  GMAIL_USERNAME: 'enviosyarq'
  GMAIL_PASSWORD: 'enviosyarq2017'
  URL: 'https://envios-ya-obligatorio.mybluemix.net'
  URLAPIKG: 'https://delivery-rates.mybluemix.net/'
  USERAPI: '180121'
  PASSWORDAPI: 'EDQBtYNNP2H1'