development:
  GMAIL_USERNAME: 'enviosyarq'
  GMAIL_PASSWORD: 'enviosyarq2017'
  URL: 'https://obligatorio1-erreperez.c9users.io/signup'
production:
  GMAIL_USERNAME: 'enviosyarq'
  GMAIL_PASSWORD: 'enviosyarq2017'
  URL: 'https://envios-ya-obligatorio.mybluemix.net'